// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMzQDEe_wRd_uxtm4FXC086pOkAUsAhw',
    appId: '1:1087149908046:web:219a68f51787f05bb6a31f',
    messagingSenderId: '1087149908046',
    projectId: 'diplomasurvey-cb0a5',
    authDomain: 'diplomasurvey-cb0a5.firebaseapp.com',
    storageBucket: 'diplomasurvey-cb0a5.firebasestorage.app',
    measurementId: 'G-838EVBCR7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10-YjJCxcs_jATgK53NeOLfAwOIccmxw',
    appId: '1:1087149908046:android:68275b500b522c5eb6a31f',
    messagingSenderId: '1087149908046',
    projectId: 'diplomasurvey-cb0a5',
    storageBucket: 'diplomasurvey-cb0a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiKzUefTt5bRFxIXQEpiBfSbxE_qIgbck',
    appId: '1:1087149908046:ios:a06fb84cd22559f0b6a31f',
    messagingSenderId: '1087149908046',
    projectId: 'diplomasurvey-cb0a5',
    storageBucket: 'diplomasurvey-cb0a5.firebasestorage.app',
    iosClientId: '1087149908046-c0mqta1av244sa5o5a58v13l50r1rhs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomaSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiKzUefTt5bRFxIXQEpiBfSbxE_qIgbck',
    appId: '1:1087149908046:ios:a06fb84cd22559f0b6a31f',
    messagingSenderId: '1087149908046',
    projectId: 'diplomasurvey-cb0a5',
    storageBucket: 'diplomasurvey-cb0a5.firebasestorage.app',
    iosClientId: '1087149908046-c0mqta1av244sa5o5a58v13l50r1rhs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomaSurvey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeMzQDEe_wRd_uxtm4FXC086pOkAUsAhw',
    appId: '1:1087149908046:web:15b77d4453bce049b6a31f',
    messagingSenderId: '1087149908046',
    projectId: 'diplomasurvey-cb0a5',
    authDomain: 'diplomasurvey-cb0a5.firebaseapp.com',
    storageBucket: 'diplomasurvey-cb0a5.firebasestorage.app',
    measurementId: 'G-Z4J0B86K18',
  );
}
